name: tested
description: A testing library based on package:test
version: 1.0.1
homepage: https://github.com/Ampless/tested

environment:
  sdk: ^3.0.0

dependencies:
  lints: ^4.0.0
  meta: ^1.0.0
  test: ^1.0.0
